#! /bin/bash -x
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    echo "installing..."
elif [[ "$OSTYPE" == "linux-gnueabihf" ]]; then
    echo "installing..."
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "unsupported OS"
    exit
elif [[ "$OSTYPE" == "cygwin" ]]; then
    echo "unsupported OS"
    exit
elif [[ "$OSTYPE" == "msys" ]]; then
    echo "unsupported OS"
    exit
elif [[ "$OSTYPE" == "win32" ]]; then
    echo "unsupported OS"
    exit
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo "unsupported OS"
    exit
else
    echo "unsupported OS"
    exit
fi
# install critial tools
sudo apt update
sudo apt install -y expect jq curl git

# install go
ARCH="$(dpkg --print-architecture)"
echo "Downloading $ARCH"
if [[ "$ARCH" == "arm64" ]]; then
    GOLOC="https://go.dev/dl/go1.23.1.linux-arm64.tar.gz"
elif [[ "$ARCH" == "amd64" ]]; then
    GOLOC="https://go.dev/dl/go1.23.1.darwin-amd64.pkg"
fi
sudo apt-get remove golang-go
sudo apt-get remove --auto-remove golang-go
wget $GOLOC
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go*tar.gz
go version
rm go*gz
sudo apt install -y protobuf-compiler 
sudo apt install -y protoc-gen-go protoc-gen-go



