#! /bin/bash -x
# install critial tools
sudo apt update
sudo apt remove -y awscli # remove v1 to make way to install v2
sudo apt install -y expect jq curl git
# install AWS CLI
wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip"
unzip -o awscliv2.zip
sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
rm -Rf aws awscliv2.zip
# install SAM
wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -O sam.zip
unzip sam.zip -o -d sam-installation
sudo ./sam-installation/install
sam --version
rm -Rf ./sam-installation sam.zip
# install NVM
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
cat << "EOF" >> $HOME/.profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
EOF
source ~/.profile
nvm install 16
nvm use 16
npm install -g npm nodejs typescript aws-sdk aws-cdk yarn
#
wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
go version
rm go1.18.3.linux-amd64.tar.gz


